import Head from "next/head";
import BigNavbar from "./BigNavbar";
import SubScribe from "./SubScribe";
import Footer from "./Footer";
import ScrollToTop from "./ScrollToTop";

const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <BigNavbar />
      {children}
      <ScrollToTop />
      <SubScribe />
      <Footer />
    </>
  );
};

export default Layout;
